### ISSUE TITLE
Not able to expand or collapse downwards

### ISSUE THREAD

**Issue by tbshrr** [BALKANGraph/FamilyTreeJS#1]
I've tried all the way to enable expand and collapse like the one in OrgJs Tree. But not able to expand and collapse. Let me know if am missing something

**Comment by ZornitsaPesheva** [comment]
I have creswted an example for you: 
https://code.balkan.app/family-tree-js/expand-colllapse#JS

**Comment by tbshrr** [comment]
> I have created an example for you: https://code.balkan.app/family-tree-js/expand-colllapse#JS

Thanks for the help. But this doesn't work when there is a partner. If its just a single parter it works but not when there is a partner. Plus shows but minus doesn't. Below is the fiddle for the same example you gave

https://jsfiddle.net/ux2p1bcL/

**Comment by ZornitsaPesheva** [comment]
We have created this demo for you:
https://code.balkan.app/family-tree-js/expand-colllapse#JS

**Comment by ZornitsaPesheva** [comment]
I have added minus here: https://code.balkan.app/org-chart-js/minus#JS
