### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by sherif816** [BALKANGraph/FamilyTreeJS#103]
Hi, is it possible to use FamilyTree in offline mode? We are using offline intranet, I try it in our app, but I am getting error:
Failed to load resource: net::ERR_NAME_NOT_RESOLVED au-e-balkangraph.azurewebsites.net/api/OrgChartJS:1
I got many of the same type, looks like one error for each language.

**Comment by ZornitsaPesheva** [comment]
The licensed version works in offline mode.
