### ISSUE TITLE
how to change the color of node tree menu

### ISSUE THREAD

**Issue by Ullas-A-2000** [BALKANGraph/FamilyTreeJS#106]
<img width="746" alt="Screenshot 2024-05-08 at 1 14 03 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/137074479/c7f11e93-ed9a-4514-b34d-3b1f5b1ae4f2">

i want to change the color of this icon but was not able to can you help!!
there is no instructions for this in the official documentation also

**Comment by ZornitsaPesheva** [comment]
Hi, here is how you can change the color with CSS:
```
#base_tree_menu path, ellipse {
  fill: red !important
}
```

**Comment by Ullas-A-2000** [comment]
it worked thanks

**Comment by ZornitsaPesheva** [comment]
It works without !important too, but I forgot to remove it.
