### ISSUE TITLE
How to get events on node event on Click only ?

### ISSUE THREAD

**Issue by gopi15699sptr** [BALKANGraph/FamilyTreeJS#107]
I am using swipe on top of the card using - `nodeMouseClick: FamilyTree.action.pan,`
also 
`family.onNodeClick((args) => {
      console.log("onClick",args)
  });`
  
  In this above mentioned event getting triggered onnodeClick and also swipe top of the card . I want to trigger only on node click
  
  
<img width="634" alt="Screenshot 2024-05-08 at 10 22 33 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/106144730/8838d0bd-5a8f-452a-9bf9-d44d11177a46">

**Comment by gopi15699sptr** [comment]
Actually , I want to trigger a event to show customized edit form on click , but when I swipe on top of the card also edit form get triggered , thats the issue

**Comment by ZornitsaPesheva** [comment]
But we use the same option for edit and pan. So you can use pan or edit.
To open edit, you can use double click: https://code.balkan.app/org-chart-js/open-details-on-double-click#JS

**Comment by gopi15699sptr** [comment]
Is this is only option to resolve my issue ?

**Comment by ZornitsaPesheva** [comment]
I will check and let you know.

**Comment by ZornitsaPesheva** [comment]
We have created a code demo for you:
https://code.balkan.app/org-chart-js/pan-and-click#JS

**Comment by gopi15699sptr** [comment]
Yes great! , its working , but one more scenario missed which is on click on node Tree menu also event gets triggered , we node want that , only want to get event trigger on node click
<img width="674" alt="Screenshot 2024-05-09 at 2 10 38 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/106144730/089dd1fb-cf25-4a7a-9a13-41109601b146">

**Comment by ZornitsaPesheva** [comment]
The event onNodeClick is not triggered on nodeTreeMenu button click.
Did you mean something else?

**Comment by gopi15699sptr** [comment]
No , When I click on Node event is getting triggered, above mentioned issue resolved , But another issue came for when I nodeTreeMenu that time also node event getting triggered, I dont want that

**Comment by ZornitsaPesheva** [comment]
How can I reproduce the issue in the below code example?
https://code.balkan.app/family-tree-js/pan-and-click#JS
