### ISSUE TITLE
How do u determine particular node is ancestor or descendant

### ISSUE THREAD

**Issue by Ullas-A-2000** [BALKANGraph/FamilyTreeJS#109]
suppose on node click or a html class code how do we determine that a card is a ancestor of root user or descendant of root user

**Comment by ZornitsaPesheva** [comment]
This demo highlight the nodes to the root:
https://code.balkan.app/family-tree-js/highlight-selected-node#JS

**Comment by Ullas-A-2000** [comment]
<img width="1066" alt="Screenshot 2024-05-16 at 2 44 42 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/137074479/aa9989b0-8cf3-4980-ae24-9908ceb42237">

suppose yermolai kozolv is root user

his parents should be identified as ancestors 
and his children shold be identified as descendants

how?

**Comment by ZornitsaPesheva** [comment]
Please explain in steps the behavior that you need? Click on which node? Then highlight or what and which nodes exactly?

**Comment by Ullas-A-2000** [comment]
lets say ,
my name is jhon and im the root user of tree

jhon has two children ema and may
jhon has parents dexter and juliet

when i click on ema i should get descendant
when i click on dexter i should get ancestor

similarly dexters parents are also jhons ancestors so when i click on them i should get ancestors
and ema's childrens are also jhons descendants so when i click on the i should get descendants

**Comment by ZornitsaPesheva** [comment]
I have created a code demo for you:
https://code.balkan.app/family-tree-js/ancestor-or-descendant#JS

**Comment by Ullas-A-2000** [comment]
thanks
