### ISSUE TITLE
Is it possible to minimize the tree size? And zoom in and zoom out(pinch in/out)?

### ISSUE THREAD

**Issue by Prerana-das** [BALKANGraph/FamilyTreeJS#11]
<img width="1125" alt="Screenshot 2022-05-16 at 18 56 04" src="https://user-images.githubusercontent.com/32504893/168597408-42690eda-11f8-41fe-b7e9-fff1fbb33f50.png">

**Comment by ZornitsaPesheva** [comment]
You can use [initial scale](https://balkan.app/FamilyTreeJS/Docs/Layout#value) option to set the initial zoom.

**Comment by Prerana-das** [comment]
Thank you. What about zoom in and zoom out using touchpad/ mouse?

**Comment by ZornitsaPesheva** [comment]
This is the default behavior of Org Chart JS.

**Comment by Prerana-das** [comment]
I'm using family tree js. Is it possible to add zoom in and zoom out feature by using touchpad/ mouse?

For example, if we browse from mobile we easily can zoom in/out.

**Comment by ZornitsaPesheva** [comment]
Sorry, it's the same for Family Tree JS. Zoon in/out are working by default for touchpad and mouse scroll.

**Comment by Prerana-das** [comment]
Thanks

**Comment by Prerana-das** [comment]
> Sorry, it's the same for Family Tree JS. Zoon in/out are working by default for touchpad and mouse scroll.

Zoon in/out are not working by default in PC but mobile is okay. What to do?


See I just can drag .No zoom in zoom out
https://user-images.githubusercontent.com/32504893/170971657-b032c634-4e8e-4ac7-9b4c-01c497c90b18.mov

**Comment by ZornitsaPesheva** [comment]
Please check if you have in your chart configuration this and delete it:
`mouseScrool: OrgChart.action.none,`

**Comment by Prerana-das** [comment]
Thanks

**Comment by Prerana-das** [comment]
But it's too fast
