### ISSUE TITLE
customizing toolbar

### ISSUE THREAD

**Issue by Ullas-A-2000** [BALKANGraph/FamilyTreeJS#110]
<img width="134" alt="Screenshot 2024-05-20 at 4 27 30 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/137074479/010dd080-5905-4a7e-9b4e-b437a4c4ded6">

These toolbar, can i add more icons here and have a custom functionality to it??

**Comment by ZornitsaPesheva** [comment]
Here is a code demo:
https://code.balkan.app/org-chart-js/toolbar-collapse-all-button#JS
You can also create a button with the same design and put it next to the toolbar.

**Comment by Ullas-A-2000** [comment]
thanks
