### ISSUE TITLE
Cursor grab icon hover the tree

### ISSUE THREAD

**Issue by gopi15699sptr** [BALKANGraph/FamilyTreeJS#114]
<img width="171" alt="Screenshot 2024-05-27 at 9 12 14 PM"
 src="https://github.com/BALKANGraph/FamilyTreeJS/assets/106144730/db9a00ff-d273-483d-9cf5-56ef54553a0e">

<img width="171" alt="Screenshot 2024-05-27 at 9 13 10 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/106144730/4797905f-987a-4a4e-865a-bd111986fee2">

To grab/ hover a tree using mouse , I need this grab effect

**Comment by ZornitsaPesheva** [comment]
Here is a code demo:
https://code.balkan.app/org-chart-js/change-cursor-on-pan-start-and-pan-end#JS

**Comment by gopi15699sptr** [comment]
Thanks @ZornitsaPesheva  it worked
