### ISSUE TITLE
Search Customization for list 

### ISSUE THREAD

**Issue by gopi15699sptr** [BALKANGraph/FamilyTreeJS#116]
<img width="340" alt="Screenshot 2024-06-03 at 2 20 13 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/106144730/9229b7f8-a839-4787-a60f-2b4a505eb377">

I want to change the default profile with gender based , like male its should be blue for females it should be pink @ZornitsaPesheva 
@plamen-peshev

**Comment by ZornitsaPesheva** [comment]
Check if this example can help:
https://code.balkan.app/org-chart-js/searchui-customization#JS

**Comment by gopi15699sptr** [comment]
> Check if this example can help: https://code.balkan.app/org-chart-js/searchui-customization#JS

Yes this helped me , Thanks @ZornitsaPesheva
