### ISSUE TITLE
Export PDF using <iframe>

### ISSUE THREAD

**Issue by gopi15699sptr** [BALKANGraph/FamilyTreeJS#117]
We are using the iframes to render balkan tree in our app . because we using server side rendering , Can you please help me with that how to generate PDF using iframes

OnReceive event how to trigger this PDF function only we needed,

**Comment by ZornitsaPesheva** [comment]
Here is an example of how you can have outside export buttons:
https://code.balkan.app/family-tree-js/outside-export-buttons#JS
If this does not help, please create an example of what you have in our code app:
https://code.balkan.app/familytreejs/getting-started#JS

**Comment by gopi15699sptr** [comment]
Thanks Resolved our issue
