### ISSUE TITLE
explain fid and mid

### ISSUE THREAD

**Issue by Ullas-A-2000** [BALKANGraph/FamilyTreeJS#118]
what does fid and mid mean in the data structure of balkan

nodes: [
        { id: 1, pids: [2], name: "Amber McKenzie", gender: "female" },
        { id: 2, pids: [1], name: "Ava Field", gender: "male" },
        { id: 3, mid: 1, fid: 2, name: "Peter Stevens", gender: "male" }
    ]

**Comment by ZornitsaPesheva** [comment]
fother id and mother id
