### ISSUE TITLE
Customisation of dynamic val

### ISSUE THREAD

**Issue by Ullas-A-2000** [BALKANGraph/FamilyTreeJS#121]
i want to convert the name to uppercase using some inbuilt js functions
how do i do it here

<img width="930" alt="Screenshot 2024-06-11 at 1 53 56 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/137074479/424a1ecb-fae6-4d25-a54b-770b8ce996aa">

{val.toUpperCase()} // this is not woking!!

**Comment by ZornitsaPesheva** [comment]
Here is a code demo:
https://code.balkan.app/family-tree-js/convert-to-upper-case#JS
