### ISSUE TITLE
Tree state and position

### ISSUE THREAD

**Issue by Ullas-A-2000** [BALKANGraph/FamilyTreeJS#122]
I have implemented balkan tree by integrating backend database, and calling api for the tree data ,

The problem I'm facing is, every time I add a person using add member, I have to refresh the api, but in that time the tree is not staying in that position, it is refreshing back to it's initial state, please provide a solution for this, 

FYI :- i tried states of localstorage as per your documentation but did not work correctly for me

@plamen-peshev @ZornitsaPesheva

**Comment by ZornitsaPesheva** [comment]
Could you please reproduce the issue in a simple code example?:
https://code.balkan.app/familytreejs/getting-started#JS

**Comment by Ullas-A-2000** [comment]
https://github.com/BALKANGraph/FamilyTreeJS/assets/137074479/13f39933-c04e-47e0-b44a-3cd01ac29c21

please refer this recording
tree is going to its initial position after adding member and calling api 

@plamen-peshev @ZornitsaPesheva

**Comment by ZornitsaPesheva** [comment]
Having the below example:
https://code.balkan.app/family-tree-js/122#JS
adding a parent to amber's grandfather you get this:
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/19305472/56d20d83-be61-4436-9f6d-ce9d5b5811ac)
Please send us a screenshot of what you expect.

**Comment by gopi15699sptr** [comment]
> Having the below example: https://code.balkan.app/family-tree-js/122#JS adding a parent to amber's grandfather you get this: ![image](https://private-user-images.githubusercontent.com/19305472/339649239-56d20d83-be61-4436-9f6d-ce9d5b5811ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDYyMzUsIm5iZiI6MTcxODM0NTkzNSwicGF0aCI6Ii8xOTMwNTQ3Mi8zMzk2NDkyMzktNTZkMjBkODMtYmU2MS00NDM2LTlmNmQtY2U5ZDViNTgxMWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA2MTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYzg2NzRiMDlhODMzYTAzY2VmNDkzMTYwZWUzZDJiMjIxN2IxYzJlMmYwYjJiOGYxNmQ5NmI5OThjZmM3ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VB9NpFiRzW6mUGUxezX_AoizxAHIVMfZHz0fzUsVStA) Please send us a screenshot of what you expect.

@ZornitsaPesheva 

In above mentioned video https://github.com/BALKANGraph/FamilyTreeJS/issues/122#issuecomment-2167235461, WN card having the external tree , If I add any member that relative to the WN external and after called the API , that position was changed in that video , Actually we want to stay in same external tree WN

**Comment by plamen-peshev** [comment]
What is WN?

We have watched the video and looks that it works as expected, what exactly is the issue, can you explain step by step what is the Actual Behavior and what is the Expected Behavior

**Comment by gopi15699sptr** [comment]
> What is WN?
> 
> We have watched the video and looks that it works as expected, what exactly is the issue, can you explain step by step what is the Actual Behavior and what is the Expected Behavior

To see the video , WN is card see the profile picture
<img width="954" alt="Screenshot 2024-06-14 at 12 42 56 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/106144730/a57cbb9f-457f-449c-932b-f558f7e1ddbd">


Actual Behaviour
When we try to add new member(WN card family) in our tree we calling that API , our backend will provides the data then balkan tree gets loaded actually refreshing, SO again tree gets rendered GN family only , 

Expected Behaviour
We want to which is the latest member we added , that external tree should show like when I 

- Add WN then WN  family should open , 
- add relatives to GN then GN family open after refreshing

**Comment by ZornitsaPesheva** [comment]
On the video, you are adding members only to the GN branch. How the issue is related to the video?

**Comment by gopi15699sptr** [comment]
https://github.com/BALKANGraph/FamilyTreeJS/assets/106144730/1f173261-598c-4909-beae-40c95c953b8a



My Bad , check this one

**Comment by ZornitsaPesheva** [comment]
Now please edit this example, so we can reproduce the issue in it, as we don't know what you have in your code that is causing the issue:
https://code.balkan.app/family-tree-js/122#JS

**Comment by Ullas-A-2000** [comment]
https://github.com/BALKANGraph/FamilyTreeJS/assets/137074479/5059de22-a9f1-4e16-bc25-97e99bb406c0

please check this after i traverse too much in tree and add a member the tree loads again due to new data and it refreshes the tree position to initial state

this reset position we dont want even after refresh

**Comment by ZornitsaPesheva** [comment]
I think I already understood the issue, but I need you to create an example in our code app and send us the link, so we can see what is causing that issue.

**Comment by gopi15699sptr** [comment]
> I think I already understood the issue, but I need you to create an example in our code app and send us the link, so we can see what is causing that issue.



var family = new FamilyTree(document.getElementById("tree"), {
    mouseScrool: FamilyTree.action.none,
    nodeBinding: {
        field_0: "name"
    },
    nodeTreeMenu : true,
    sticky: false,
    state: {
        name: 'StateForMyFamilyTree',
        readFromLocalStorage: true,
        writeToLocalStorage: true,
    },
    nodes: [
        { id: 1, pids: [2], name: "Amber McKenzie", gender: "female" },
        { id: 2, pids: [1], name: "Ava Field", gender: "male" },
        { id: 3, mid: 1, fid: 2, name: "Peter Stevens", gender: "male" },
        { id: 4, mid: 1, fid: 2, name: "Savin Stevens", gender: "male" },
        { id: 5, mid: 1, fid: 2, name: "Emma Stevens", gender: "female" }


    ]


**After adding member and refreshing the page, its giving an error tree is not rendering**
<img width="1331" alt="Screenshot 2024-06-14 at 3 39 09 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/106144730/87943ceb-8f34-49e5-ba19-cf844de66384">

**Comment by ZornitsaPesheva** [comment]
When you refresh a page in Code app it will load the initial data. Why do you refresh the page? You don't need to refresh the page when you add a member.
