### ISSUE TITLE
dynamic orientation change

### ISSUE THREAD

**Issue by Ullas-A-2000** [BALKANGraph/FamilyTreeJS#123]
im using a custom template in balkan
ive set custom node sizes and styles
below is a small example

<img width="1287" alt="Screenshot 2024-06-15 at 1 15 55 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/137074479/f1358354-991f-4a97-a963-1ccbb90271f8">

```
 if(rotateBtn){
            rotateBtn.addEventListener("click", function () {
                if(that.obj.config.orientation == 0){
                    data.orientation = 'left'
                    that.obj.setOrientation(3)
                    return;
                }
                data.orientation = 'nd'
                that.obj.setOrientation(0)
            });
  }
```

this code im using to change orientation , the orientation is changing but,  also i want to change node sizes on orientation change how to do it

**Comment by ZornitsaPesheva** [comment]
Please edit this example to isolate the issue:
https://code.balkan.app/org-chart-js/orientation#JS
