### ISSUE TITLE
delete dependencies

### ISSUE THREAD

**Issue by Ullas-A-2000** [BALKANGraph/FamilyTreeJS#124]
whenever i want to delete a card from tree
and delete is not possible due to dependent members
i need a list of all the dependent members due to which i cant delete

example : 
person A has spouse person B
person B has father Person C

if i try to delete person B i need to show the pop up
"delete Person C first and then delete Person B"

how?

@ZornitsaPesheva @plamen-peshev

**Comment by ZornitsaPesheva** [comment]
You can use family.getNode(id) and see all the properties of the object.

**Comment by Ullas-A-2000** [comment]
can we get who are the members due to which i cant delete the card

**Comment by ZornitsaPesheva** [comment]
Out of the box you cannot. It is possible to do it, but it is too complicated.

**Comment by Ullas-A-2000** [comment]
can you give me the approach

**Comment by ZornitsaPesheva** [comment]
You need to override the method:
```

FamilyTree.prototype.canRemove = function (id) { 
    var node = this.getNode(id);
    if (!node){
        return false;
    }


    var mnode =  this.getNode(node.mid);
    var fnode =  this.getNode(node.fid);

    var hasChildren = node.ftChildrenIds.length > 0;
    var hasOnePartnerWithTheSameChildren = false;
    var hasPartners = node.pids.length > 0;
    var hasMoreThenOnePartner = node.pids.length > 1;

    if (node.pids.length == 1){
        var partnerNode =  this.getNode(node.pids[0]);        
        hasOnePartnerWithTheSameChildren = node.ftChildrenIds.compare(partnerNode.ftChildrenIds);
    }
    

    if ((mnode || fnode) && !hasChildren && !hasPartners){
        return true;
    }

    if ((!mnode && !fnode) && !hasChildren && !hasMoreThenOnePartner && hasPartners && !hasOnePartnerWithTheSameChildren){
        return true;
    }

    
    if ((!mnode && !fnode) && hasChildren && hasOnePartnerWithTheSameChildren){
        return true;
    }

    if ((!mnode && !fnode) && hasChildren && !hasOnePartnerWithTheSameChildren){
        return true;
    }

    if ((!mnode && !fnode) && !hasChildren && hasOnePartnerWithTheSameChildren){
        return true;
    }
    
    return false;
}
```

**Comment by gopi15699sptr** [comment]
@ZornitsaPesheva  What is ppid ?

**Comment by Ullas-A-2000** [comment]
<img width="641" alt="Screenshot 2024-06-20 at 1 10 06 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/137074479/4a12ba33-2553-4f09-8d02-bf1d98f44da7">



here **SH** is a person from the tree who is a part of root user family
but **WH** and **AW** is external person coming to family

how to detect this

**Comment by ZornitsaPesheva** [comment]
> @ZornitsaPesheva What is ppid ?

Parent partner ID

**Comment by ZornitsaPesheva** [comment]
> <img alt="Screenshot 2024-06-20 at 1 10 06 PM" width="641" src="https://private-user-images.githubusercontent.com/137074479/341317845-4a12ba33-2553-4f09-8d02-bf1d98f44da7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzA2ODgsIm5iZiI6MTcxODg3MDM4OCwicGF0aCI6Ii8xMzcwNzQ0NzkvMzQxMzE3ODQ1LTRhMTJiYTMzLTI1NTMtNGYwOS04ZDAyLWJmMWQ5OGY0NGRhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwNzU5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTQyM2MzYmQxZWY2Mjc4Yjg4MjJiMDczYzYxNzRmZDJjZWQ5NTkwYzIzMDZiNzRkNzhhODBjMjM1OTc4ZjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f-f7aR0TCEnkQowbVaXOiWnFl-7uPyq-v2oKsq8PoDs">
> here **SH** is a person from the tree who is a part of root user family but **WH** and **AW** is external person coming to family
> 
> how to detect this

If they are partners of SH, that meant that they are "external"

**Comment by Ullas-A-2000** [comment]
i did some changes in family.js file and deployed to our server
we are using your SSR approach using express js

we are loading tree using iframe
but those familytree.js file changes are not reflecting there
