### ISSUE TITLE
Authorize Domains

### ISSUE THREAD

**Issue by gopi15699sptr** [BALKANGraph/FamilyTreeJS#125]
<img width="812" alt="Screenshot 2024-06-25 at 1 23 33 PM" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/106144730/9cc76a35-62b5-4745-bc14-0e1033dd1b33">

If today I added a domain , can I edit it in future ? And also What If I am using react native webview to render tree ?

**Comment by ZornitsaPesheva** [comment]
Yes, you can edit the domain in the future. You can use any environment that run JavaScript, including React Native WebView.
