### ISSUE TITLE
Seems to crash on a large data set

### ISSUE THREAD

**Issue by bobokeke0** [BALKANGraph/FamilyTreeJS#13]
I get "Uncaught RangeError: Maximum call stack size exceeded" when i try to render a large dataset. What's the limit is there's any?

**Comment by ZornitsaPesheva** [comment]
How many nodes do you have?

**Comment by bobokeke0** [comment]
I'm working with 1043 nodes

**Comment by ZornitsaPesheva** [comment]
Could you please send your data to support@balkan.app from your registration email?
You could replace the real data with a fake one. Only the relations should stay the same.

**Comment by mostepunk** [comment]
I have the same problem with data of 400 persosns

**Comment by ZornitsaPesheva** [comment]
> I have the same problem with data of 400 persosns

Create a Code example in our Code app:
https://code.balkan.app/familytreejs/getting-started#JS
or send your data to our email.
