### ISSUE TITLE
How to setup FamilyTreeJS in nextjs?

### ISSUE THREAD

**Issue by unclebay143** [BALKANGraph/FamilyTreeJS#139]
It's been a pain trying to figure how to set this up on Nextjs using the docs.

The most I've reached is the point below:
![image](https://github.com/user-attachments/assets/192c1478-4fd1-4a78-a1ea-43ff11fc0dbd)

Can anyone help with useful resources please

**Comment by unclebay143** [comment]
Sometimes, it's just blank like this
![image](https://github.com/user-attachments/assets/81a7cf0f-5d6a-4807-b0be-eb7d85afd23f)

no console error

**Comment by unclebay143** [comment]
my next config doesn't allow using require, and when used, it throws error for tailwins, and when I used ES6, it shows the same error:
![image](https://github.com/user-attachments/assets/9e40c153-8b2f-40d9-925f-622e7e04b257)



```
/** @type {import('next').NextConfig} */
import nextTranspileModules from "next-transpile-modules";
const withTM = nextTranspileModules(["@balkangraph/familytree.js"]);

const nextConfig = {};

export default withTM(nextConfig);

```

**Comment by unclebay143** [comment]
Seeking help on stackoverflow here: https://stackoverflow.com/questions/79009705/how-to-setup-balkan-familytreejs-in-nextjs-14

**Comment by ZornitsaPesheva** [comment]
What product are you asking about? FamilyTree JS or FamilyTree Maker?

**Comment by unclebay143** [comment]
> Currently there is an issue with the NPM version. Please try to use the downloaded version from here: https://balkan.app/FamilyTreeJS/Download

Ah, that makes sense, trying the link you shared.

**Comment by unclebay143** [comment]
> It should be fixed now.
Thanks, the downloaded version is working now, I actually tried it yesterday but didn't work, but it's working now.
Will keep an eye out for when the npm version will be stabled/fixed. 

Thanks for the help @ZornitsaPesheva

**Comment by unclebay143** [comment]
this has been resolved here: https://stackoverflow.com/a/79013510/7953084. Closing this issue
