### ISSUE TITLE
Limit of number of family members

### ISSUE THREAD

**Issue by aelhofy** [BALKANGraph/FamilyTreeJS#14]
When started to add my family everything was good till the moment the family members started to increase (500+)then the script stopped working, and when I decreased the number of family members  to about 150 then script started  to work back.

Could you please increase the number of family members  that can be added.

Note: same issue is with Orgchar script 

Thanks for the fantastic  project.

**Comment by ZornitsaPesheva** [comment]
Hi [aelhofy](https://github.com/aelhofy)
The limitation of the trial version is 200 nodes.
https://balkan.app/FamilyTreeJS/Docs/Evaluation

**Comment by aelhofy** [comment]
OK, do you have license for personal use and how much it is please?

**Comment by ZornitsaPesheva** [comment]
These are all the licenses that we have: https://balkan.app/FamilyTreeJS/Pricing
