### ISSUE TITLE
Adjusting Spacing Dynamically Between Siblings Based on Child Count

### ISSUE THREAD

**Issue by Omri93h** [BALKANGraph/FamilyTreeJS#152]
Hi,

I'm working with the "john" template, and I’m encountering an issue with cousins overlapping each other when siblings have multiple children. Specifically, I’d like to create more space between siblings when one or both have a larger number of children. This would prevent cousins from colliding visually.

Ideally, I’m looking to add, say, **100px of extra spacing for each child** one of the siblings has. This way, the siblings with more children are spaced farther apart, preventing overlap between their children.

Is there an existing way to dynamically adjust spacing between siblings based on their child count, or is there another recommended approach for this scenario?

Thank you!

<img width="866" alt="image" src="https://github.com/user-attachments/assets/10625da1-8dd5-4573-83db-a2916c46d8fd">
(bottom right at image)

**Comment by ZornitsaPesheva** [comment]
Hi, that overlapping should not happen. Could you please create a simple code example in our [Code app](https://code.balkan.app/familytreejs/getting-started#JS) to isolate the issue?

**Comment by ZornitsaPesheva** [comment]
Looks like you have some bug in the logic, because you have pids two times here:
![image](https://github.com/user-attachments/assets/b23983d7-f823-40d9-b5c6-268fb6ac9d89)

**Comment by Omri93h** [comment]
That was it! i can't believe i did not see that! THANKS YOU SO MUCH FOR THE HELP AND THE FAST REPLIES !!
