### ISSUE TITLE
updating node returns error

### ISSUE THREAD

**Issue by ezeagwulae** [BALKANGraph/FamilyTreeJS#16]
When updating a node with the `updateNode` method found [here](https://github.com/BALKANGraph/FamilyTreeJS/blob/9cf9aeae0abf18eb56c21630107c244a35273bdd/familytree.d.ts#L90), I'm getting the following console error 
```javascript
familytree.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at FamilyTree.updateNode (familytree.js:1:28298)
```

This is what I'm doing 
```javascript
family.on('update', function (sender, oldnode, newnode) {
  // send updated info to backend
  .....

  // redraw family tree with updated object
  sender.updateNode(newnode)

}
```

I've tried following similar instructions here https://github.com/BALKANGraph/OrgChartJS/issues/382, but still hitting a dead end. Any guidance would be helpful. The error returns when using the `updateNode` to redraw the family tree

**Comment by ZornitsaPesheva** [comment]
Hi @ezeagwulae ,

This is the right way to use the event: https://code.balkan.app/update-family-tree-js/update-node-event-listener#JS
But on Update the node is already updated. What do you need to do?

**Comment by ZornitsaPesheva** [comment]
updateNode is to update the node programmatically.
Actually we are still using it only internally.
