### ISSUE TITLE
Divorced partner node's connected dash line is replaced with a solid line

### ISSUE THREAD

**Issue by p3rv3z** [BALKANGraph/FamilyTreeJS#18]
When I expanding the divorce partner's parent nodes  by clicking the expand green icon the partner node dashed line is replaced with a solid line. How can i fix it?

**Before clicking the expand icon**
![image](https://user-images.githubusercontent.com/33283036/174755486-ef48c148-ae57-4dc2-90e0-feecdc002445.png)
**After clicking the expand icon**
![image](https://user-images.githubusercontent.com/33283036/174754987-181a2aca-4870-4a6b-8eb2-294056ed8adb.png)

**Comment by ZornitsaPesheva** [comment]
Could you please edit this code to reproduce the issue:
https://code.balkan.app/family-tree-js/divorced-link#JS
