### ISSUE TITLE
Parent nodes expand icon is vainshed

### ISSUE THREAD

**Issue by p3rv3z** [BALKANGraph/FamilyTreeJS#19]
After Clicked the Jane's parent node expand icon the tree expanded

But how can I get back to previous state like the above image. See the below image there is no option to get back to the previous state.

Please help me to find any solution for this issue. Thanks

**Comment by p3rv3z** [comment]
### Here is the code

```
var family = new FamilyTree(document.getElementById("tree"), {
    mouseScrool: FamilyTree.action.none,
    nodeBinding: {
        field_0: "name"
    },
    nodes: [
        { id: 1, fid: 3, pids: [2], name: "John", gender: "male" },
        { id: 2, pids: [1], name: "Jane", gender: "female" },
        { id: 3, name: "Peter", gender: "male" },
        { id: 4, fid: 3, name: "Denice", gender:"female"},
    ]
});
```

**Comment by ZornitsaPesheva** [comment]
Thank you for reporting this. We will contact you when it is fixed.

**Comment by ZornitsaPesheva** [comment]
Hi. Did you mean the John's parents expand icon in this example?

**Comment by ZornitsaPesheva** [comment]
To be able to collapse back, you need to add button that set Jane as root.
