### ISSUE TITLE
code.balkan.app doesn't work properly via Firefox

### ISSUE THREAD

**Issue by kraart** [BALKANGraph/FamilyTreeJS#26]
Steps to reproduce:
1. Fire up Firefox (the latest version103.0.2 (64-bit)
2. Open any demo or code https://code.balkan.app/
3. The editor won't open properly as in Chrome 

![code balkan - bug](https://user-images.githubusercontent.com/10218552/184530986-9ca82af2-ebbe-4dcb-b0c5-a9c9ddcf1889.jpg)

**Comment by ZornitsaPesheva** [comment]
Fixed :)
