### ISSUE TITLE
FamiliyTreeJS limitation for sisters?

### ISSUE THREAD

**Issue by kraart** [BALKANGraph/FamilyTreeJS#27]
Hi, 
I am failing to generate a tree where two sisters have children from one man (one in blue, the second in red).

![image](https://user-images.githubusercontent.com/10218552/184551346-3f5878ec-2344-43ad-a70c-f058e4d2f9ea.png)

Here is my code: https://code.balkan.app/test-code#JS

The two issues I see:
1) For some reason "5Aleksandr"s parents disappear
2) All children are presented as being from 7Maria and 5Aleksandr
What FamilyTreeJs generates:
![image](https://user-images.githubusercontent.com/10218552/184551484-19386f09-9a62-4396-a123-0f3c159c648c.png)

Is this even possible to get achieved? A workaround? 

Thank you,
Art

**Comment by ZornitsaPesheva** [comment]
Balkan FamilyTreeJS does not support such relations.
You can try to create two different family trees. In the first one, you will see the relation with one of the sisters, and in the second one you will see the relations with the other sister, and will load the other tree on some (expand like) button click, that will be on Alexander's node.
