### ISSUE TITLE
Is there any way to show the age with the help of birtDate and deathDate/currentDate

### ISSUE THREAD

**Issue by tbshrr** [BALKANGraph/FamilyTreeJS#3]
I'm trying to show dynamic age with the help of birthDate. Is there any inbuilt tool to calculate the age?

https://jsfiddle.net/6tp5y2ko/

**Comment by ZornitsaPesheva** [comment]
I have created a demo for you: https://code.balkan.app/family-tree-js/calculate-age#JS
