### ISSUE TITLE
very basic question about Hiding elements inside the edit form

### ISSUE THREAD

**Issue by alejandrosfr1223** [BALKANGraph/FamilyTreeJS#33]
Hi!

I just want to know how to hide an element inside the edit form... Like, for example, the Gender tag.

![image](https://user-images.githubusercontent.com/95920858/200978365-3efb8ef9-439c-46fe-a9f8-f3f8587e2fe0.png)

i cant find anything, and i want to hide it.

**Comment by ZornitsaPesheva** [comment]
Example:
```
    var chart = new OrgChart(document.getElementById("tree"), {
        editForm: {
            generateElementsFromFields: false,
            elements: [
                { type: 'textbox', label: 'Nombre', binding: 'id'}  
                { type: 'textbox', label: 'Genero', binding: 'Genero'}  
            ]
        }       
    });
```
From here: [https://balkan.app/OrgChartJS/Docs/Edit](https://balkan.app/OrgChartJS/Docs/Edit)

**Comment by alejandrosfr1223** [comment]
Perfect! it worked like a Charm!
