### ISSUE TITLE
fileUploadDialog is not working properly since 1.07.2

### ISSUE THREAD

**Issue by simoespt** [BALKANGraph/FamilyTreeJS#36]
The method parameters changed after 1.07.2, on the latest versions is requiring args and callback, im using as the example:
![image](https://user-images.githubusercontent.com/44359911/205460969-3ba27f70-1608-4ffd-8df2-3f3872ba7ebc.png)
but im always facing the following error: 
![image](https://user-images.githubusercontent.com/44359911/205461018-680c5c74-ac1c-40ff-8f74-c41d85314793.png)

(I have tried diferent values on args object but without success)

I notice that https://code.balkan.app/result/family-tree-js/image-upload
is also returning the same error when trying to upload an image.

**Comment by ZornitsaPesheva** [comment]
I have changed the example:
https://code.balkan.app/family-tree-js/image-upload#JS

**Comment by simoespt** [comment]
Thanks I will apply that fix for now, but code wise that is not 100% correct because the signature of the method indicates that has 2 arguments 
![image](https://user-images.githubusercontent.com/44359911/205484261-f6d86743-fd57-472f-b6a7-e1b6daef5767.png)

**Comment by ZornitsaPesheva** [comment]
fixed
