### ISSUE TITLE
Not showing Parents if mid and fid are not linked together using pid

### ISSUE THREAD

**Issue by azlanali076** [BALKANGraph/FamilyTreeJS#38]
If we have a node of id 1 and it has a mother id 2 and father id 3 we are creating nodes like 
```
[
{
id: 1,
name: 'Child',
mid: 2,
fid: 3
},
{
id: 2,
name: 'Mother'
},
{
id: 3,
name: 'Father'
}
]
```

upon clicking on child node in tree to expand parents its crashing the whole tree

**Comment by azlanali076** [comment]
@ZornitsaPesheva i know but what if for some reason i cannot pass pids

**Comment by ZornitsaPesheva** [comment]
You should pass pids to the family tree js. 
It cannot work without pids.
