### ISSUE TITLE
Create multiple (at least more than three) parents and one child FamilyTreeJs

### ISSUE THREAD

**Issue by aleresoftware** [BALKANGraph/FamilyTreeJS#42]
Hi there,
Based on my use cases of my project, I need to build a diagram where parents are more than three and their child must be only one. Is there any way of build such relationship?

Thank you 

Example like this
![three parents one child](https://user-images.githubusercontent.com/116687484/207478859-babc1185-78e3-4bf0-9cd0-fd938240bedc.PNG)

**Comment by ZornitsaPesheva** [comment]
You can use orientation.bottom:
https://balkan.app/OrgChartJS/Docs/Layout#bottom

**Comment by aleresoftware** [comment]
Hi there,
Thank you for your reply. But I realised that my diagram was not completely explainable to describe my use cases. Here below I have attached the image, very similar to my use case, where I need to build relationship with respect to Q4 (Q4 must have three parent ids and two children ids). Is there any way of building such relationship.

Thank you.

Example like this

![three parents one child full diagram](https://user-images.githubusercontent.com/116687484/207744887-2ce4d86c-fad2-4ea4-8bb6-2e17820f035d.PNG)

**Comment by ZornitsaPesheva** [comment]
In our First look demo if you expand the root node up, you will see that you can have two parents and three children:
https://balkan.app/OrgChartJS/Demos/FirstLook
![image](https://user-images.githubusercontent.com/19305472/207773471-7501a997-5d1b-45f4-9038-3a9aaa350348.png)

**Comment by aleresoftware** [comment]
what about creating three parents and two children for that node? is it possible?

**Comment by ZornitsaPesheva** [comment]
Yes, it is possible. Here is the doc:
https://balkan.app/OrgChartJS/Docs/SubTrees#simulate

**Comment by aleresoftware** [comment]
Thank you
