### ISSUE TITLE
User Changes are lost after editing

### ISSUE THREAD

**Issue by GalinaLapushinskaya** [BALKANGraph/FamilyTreeJS#45]
1. Go to Balkan Tree demo application: https://balkan.app/FamilyTreeJS/Demos/first-look
2. Click on top left menu for the user Rowan Annable, template users are added
3. Click on Rowan to open Edit form
4. Check his name to Rowan Annable 123 and click Save and close
5. Now, when user name is changed on a tile, click on the "X" button in the top left menu to remove template members:

- expected behavior: Rowan's user details changes are saved
- actual behavior: Rowan's name returned to Rowas Annable and changes are lost

Also, is there a way to return from the view where use adding members to a tile to  normal view programmatically?

**Comment by toshioue** [comment]
Same here. I am running the BalkanTree Library in Angular when attempting to save edits made to an existing node. 
This is the error i receive in the console:

core.mjs:9095 ERROR TypeError: Cannot set property 3 of [object Module] which has only a getter
    at FamilyTree.update (familytree.js:1:20865)
    at FamilyTree._fireUpdate_addUpdateRemove (familytree.js:1:30327)
    at FamilyTree.updateNode (familytree.js:1:29777)
    at HTMLButtonElement.<anonymous> (familytree.js:1:46684)
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at core.mjs:25299:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25299:36)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Object.onInvokeTask (core.mjs:25607:33)
    at _ZoneDelegate.invokeTask (zone.js:408:60)

**Comment by plamen-peshev** [comment]
We have addressed the issue in the latest version 

Now you cannot edit a node when node tree menu is opened 

Clear your browser cache and test [here ](https://code.balkan.app/result/family-tree-js/first-look)

**Comment by toshioue** [comment]
Thank you, the issue has been resolved on my end!

**Comment by GalinaLapushinskaya** [comment]
The issue was resolved for me too, thank you
