### ISSUE TITLE
HideTreeMenu doesn't hide the "Add members" menu

### ISSUE THREAD

**Issue by GalinaLapushinskaya** [BALKANGraph/FamilyTreeJS#47]
HideTreeMenu is not working for me all the time. I can't find the exact pattern, sometimes it works, sometimes stops to work. We also save state in the local storage. Please advise.

**Comment by ZornitsaPesheva** [comment]
We have tried to isolate the issue with no avail.
Code: https://code.balkan.app/hidetreemenu-doesn't-hide-the-add-members#JS
Result: https://code.balkan.app/result/hidetreemenu-doesn't-hide-the-add-members

**Comment by GalinaLapushinskaya** [comment]
I found the issue. menu is method is working as expected
