### ISSUE TITLE
React Functional Component Example of OrgChart

### ISSUE THREAD

**Issue by Rajesh-Gandla** [BALKANGraph/FamilyTreeJS#48]

**Comment by ZornitsaPesheva** [comment]
This is all we have for React
https://balkan.app/FamilyTreeJS/Docs/React

**Comment by wanyouyu** [comment]
https://jp-e-balkangraph.azurewebsites.net/api/OrgChartJS.
Can it be shared?   I see it  in family-tree.js .

**Comment by ZornitsaPesheva** [comment]
We have this doc page for Family Tree JS and for Org Chart JS

**Comment by wanyouyu** [comment]
Thank you. I'll read that doc again
