### ISSUE TITLE
Limitation on number of nodes?

### ISSUE THREAD

**Issue by MalcolmMcFly** [BALKANGraph/FamilyTreeJS#51]
I am mapping out my extended family and have 64 nodes. I am getting the following error:

<img width="581" alt="Screenshot 2023-01-29 at 10 32 08 PM" src="https://user-images.githubusercontent.com/15109016/215387973-6c2c205e-61cb-4e9d-978e-237520461d3a.png">

Is there a limit to how many nodes (family members) I can add to a tree?

**Comment by ZornitsaPesheva** [comment]
In the trial version the limit is 200 nodes, but it looks like you have some issue with the data.
Please create a simple example in Code to reproduce the error: 
https://code.balkan.app/familytreejs/getting-started#JS
