### ISSUE TITLE
Editable and non-editable items in editUI

### ISSUE THREAD

**Issue by aespogom** [BALKANGraph/FamilyTreeJS#52]
Hi everyone!
I am building a tree in Angular 13.
I would like to know if it is possible to disable some inputs from editUI but not all of them.
My configuration now is: 
`

```
  chart = new FamilyTree(tree, {
            template: 'john',
            orderBy: "birthday" ,
            lazyLoading: true,
            enableSearch: false,
            mouseScrool: FamilyTree.action.ctrlZoom,
            orientation: FamilyTree.orientation.top,
            editForm: {
              generateElementsFromFields: false,
              addMore: null,
              addMoreBtn: null,
              addMoreFieldName: null,
              elements: [
                { type: 'textbox', label: 'HDL', binding: 'hdl'},
                { type: 'textbox', label: 'LDL', binding: 'ldl'},
                { type: 'textbox', label: 'Custom', binding: 'custom', vlidators: { required: 'Is required'}}
              ],
             ...
```

`

What I want to do is to be able to edit "custom" but disable "HDL" and "LDL" fields. 

<img width="925" alt="image" src="https://user-images.githubusercontent.com/94437464/215447857-7d72ec50-18f3-4820-995f-20b54a378f37.png">

I did not find anything in the documentation.
Thank you for your help!!

**Comment by ZornitsaPesheva** [comment]
Here is an example: https://code.balkan.app/org-chart-js/read-only-element#JS

**Comment by aespogom** [comment]
Works smoothly!
Thank you so much for your help!
Have a great week
