### ISSUE TITLE
NaN error 

### ISSUE THREAD

**Issue by PatB1234** [BALKANGraph/FamilyTreeJS#53]
I am creating a family tree, the first few nodes are rendering fine but then When I try to search for the rest of the nodes that are not appearing, they show up in the search bar. But when clicked, they give they following error.

![image](https://user-images.githubusercontent.com/80209204/215840961-177a7339-e852-4c19-9b52-1e6ad9a7f022.png)

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue in a simple code example:
https://code.balkan.app/orgchartjs/getting-started#JS
