### ISSUE TITLE
200 nodes limites

### ISSUE THREAD

**Issue by PLLX76** [BALKANGraph/FamilyTreeJS#56]
Hello, I am a minor person (no budget) and at the moment I undertook to make a family tree with your bookstores. The limit of nodes is 200 but while I have 127 it tells me that I have exceeded the limit of 200 nodes thank you for your help

**Comment by ZornitsaPesheva** [comment]
Your trial may have expired.
You can check the number of nodes this way:
console.log(family.config.nodes.length);

**Comment by PLLX76** [comment]
thank you

**Comment by PLLX76** [comment]
Yes, it is well written 127 nodes

**Comment by PLLX76** [comment]
Since I don't have a budget, do you have any advice to give me to find a solution so that I can continue to run my site?

**Comment by ZornitsaPesheva** [comment]
Sorry, the free version is a trial.
