### ISSUE TITLE
Arrows too nearby eachother

### ISSUE THREAD

**Issue by HolyOne** [BALKANGraph/FamilyTreeJS#60]
I have difficulty to see whose children is who especially when people have multiple children from multiple wifes

These features should be great for a much better UI
1) An option to highlight the node and the arrows from it,
2) An option to Highlight children and wifes.
3) An option to always have a constant distance from past generations. I mean I see some children bellow, wifes stacked top of each other on left and right. It is great for small family tree but not for big trees

**Comment by ZornitsaPesheva** [comment]
Here are some example for highlight:
https://code.balkan.app/family-tree-js/highlight#JS
https://code.balkan.app/family-tree-js/highlight-selected-node#JS
For 3: Can you show us in a screenshot what you need?

**Comment by HolyOne** [comment]
wow the samples are just what I was suggesting.
For 3, this is much easier to understand

![image](https://user-images.githubusercontent.com/293601/226113259-a852141e-1b8d-43c1-aa5a-ebb75b2cb8ea.png)

**Comment by ZornitsaPesheva** [comment]
You can try with levelSeparation
https://code.balkan.app/family-tree-js/distance-between-generations#JS

Or you want all the wives to be on the same level?

**Comment by HolyOne** [comment]
yes but it just assigns the distance. what I acually tried to achieve was disable vertical stacking of wifes. so each generation would be perfectly horizantal

**Comment by ZornitsaPesheva** [comment]
No, this is not possible with Family Tree JS.
