### ISSUE TITLE
Property Dialog Needs Improvements

### ISSUE THREAD

**Issue by HolyOne** [BALKANGraph/FamilyTreeJS#61]
I have some family data and I have images.
The properties bar shows image urls. I cannot hide them. (The labels dont have proper Id/classnames so I couldnt hide)

Also Additionaly I want to place extra controls/html on top of properties dialog to show extra info but the component should support this.

![image](https://user-images.githubusercontent.com/293601/226083532-4922caf4-bd7a-4ad1-a60a-9801c763df64.png)

Maybe if there was an event when the properties dialog opens, I could inject my own controls.

**Comment by ZornitsaPesheva** [comment]
Here is how to hive the link:

```
    var family = new FamilyTree(document.getElementById("tree"), {
        editForm: {
            generateElementsFromFields: false,
            elements: [
                { type: 'textbox', label: 'Full Name', binding: 'Name'},
                { type: 'textbox', label: 'Photo Url', binding: 'ImgUrl', btn: 'Upload'}        
            ]
        }       
    });
```

Here is the doc page: https://balkan.app/FamilyTreeJS/Docs/Edit#configure
