### ISSUE TITLE
Undefined stpid

### ISSUE THREAD

**Issue by Faran61** [BALKANGraph/FamilyTreeJS#62]
Good day! I faced the issue 'Cannot read properties of undefined (reading 'stpid')'. It happened after importing json, so then I closed the project. I added another data in code, then reran it but it still gives me undefined stpid. I tried the same library in another project, it works there after I reran it, so undefined stpid was disappeared. Because of this error, the tree cannot be drawn.

I am looking forward to your immediate answer. Thank you beforehand!
Best regards!

**Comment by ZornitsaPesheva** [comment]
Do you use the same version in both cases?
It is licensed?

**Comment by Faran61** [comment]
yes, but it is not licensed

**Comment by daxxac** [comment]
How to check if the version is expired? I have the same error in console.
