### ISSUE TITLE
Fix the view of the tree

### ISSUE THREAD

**Issue by daxxac** [BALKANGraph/FamilyTreeJS#66]
Is there any way to fix the broken view?

<img width="631" alt="image" src="https://github.com/BALKANGraph/FamilyTreeJS/assets/121355466/4c8454ba-350f-4490-a0ce-46155cc178e6">

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue in a simple example:
https://code.balkan.app/org-chart-js/simple-example#JS

**Comment by daxxac** [comment]
Thank you, https://code.balkan.app/broken-tree-view#JS

so according to the the data now:
1) on opening the tree for the node `621FA1433EA7B299411C265BA6FA1CCD` it looks like on the picture above
2) I have initial node, but i see another couple of nodes shown on start (grandfather and his second wife), any way to hide them?

**Comment by ZornitsaPesheva** [comment]
You have some gaps in the data.
For example, if you have here 621FA20909D1660B1167AD6FEBB3608D in pids here:
`
  {
    "id": "621FA21F635B3CA1E729B51BA338B2D1",
    "mid": null,
    "fid": null,
    "pids": [
      "621FA20909D1660B1167AD6FEBB3608D"
    ]
  },
`
You should have 621FA21F635B3CA1E729B51BA338B2D1 in pids here:

`
  {
    "id": "621FA20909D1660B1167AD6FEBB3608D",
    "mid": "621FA21F38051C9DE729B51BA338B2D1",
    "fid": "621FA21F0E628C99E729B51BA338B2D1",
    "pids": []
  },
`

**Comment by daxxac** [comment]
thanks, i'll check again

**Comment by daxxac** [comment]
Thank you! It helped a lot! 👍
