### ISSUE TITLE
Initilly center tree on one node

### ISSUE THREAD

**Issue by martesabt** [BALKANGraph/FamilyTreeJS#7]
Hi,
I would like to know if it's possible to initially center the tree view on one node.

If it's not possible it could be a good improvement.

Thanks!

**Comment by ZornitsaPesheva** [comment]
You can use this:
```
family.on('init', function(){
    family.center(5);
})
```

**Comment by martesabt** [comment]
Yes, that's what I needed!

Many thanks!
