### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by A2020GK** [BALKANGraph/FamilyTreeJS#71]
Hello, is it possible to translate built-in UI?

**Comment by ZornitsaPesheva** [comment]
Hi
What do you need to translate? Can you give us a list?

**Comment by A2020GK** [comment]
> Hi What do you need to translate? Can you give us a list?

I want to translate fields' names (name, gender), buttons (edit, export) and search bar.

**Comment by ZornitsaPesheva** [comment]
The field names are defined by you in the node data or in the edit form elements definitions.
This is for the search: https://balkan.app/FamilyTreeJS/Docs/Search
Can you give us a list of the buttons that you use?
It would be better to create a Code example and send us a screenshots of the buttons that you need to translate.

**Comment by A2020GK** [comment]
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/89532641/f059495a-0e4a-4570-9767-efec86a61627)
I want to translate these tips.

**Comment by A2020GK** [comment]
I want to translate these: 
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/89532641/8b358350-7d01-4249-afda-db843b07e528)

**Comment by ZornitsaPesheva** [comment]
Hi Антоний,
The text is defined in the template.
You can get the template from here and change it:
https://balkan.app/FamilyTreeJS/Docs/PredefinedTemplates#motherTemplate
Click on "Get the source code of mother template" to see the code.
