### ISSUE TITLE
URGENT Paid Version not working with react.

### ISSUE THREAD

**Issue by Laotsuit** [BALKANGraph/FamilyTreeJS#72]
We have had our trees stop working and it says.  - familytree does not contain a default export.

![WhatsApp Image 2023-08-17 at 7 03 06 AM](https://github.com/BALKANGraph/FamilyTreeJS/assets/78855562/9b7d372c-b6f9-4d49-9c3d-0932424edf4f)
39ac2fdf-57f8-4779-8f18-dae5122226a9)

**Comment by ZornitsaPesheva** [comment]
Did you follow this installation instruction:
https://balkan.app/FamilyTreeJS/Docs/InstallLicensedversion#react
