### ISSUE TITLE
Urgent

### ISSUE THREAD

**Issue by Laotsuit** [BALKANGraph/FamilyTreeJS#73]
Since we converted from the free to the paid version onUpdateNode function is not working

**Comment by ZornitsaPesheva** [comment]
Please create a simple example here to isolate the issue:
https://code.balkan.app/org-chart-js/simple-example#JS

**Comment by azlanali076** [comment]
I can create a simle example there but the code is same i just replaced the import from family tree package to file which we downloaded after pucrchasing the family tree library

**Comment by ZornitsaPesheva** [comment]
But in this code there is no onUpdateNode function

**Comment by ZornitsaPesheva** [comment]
Please send an HTML example with your licensed FamilyTreeJS file to our email, if you still have issues.
support@balkan.app

**Comment by azlanali076** [comment]
on my local environment the onUpdateNote function is working and on server it is not working. I can't share the code however if you guys are free at some time we can schedule a call and see the issue together?

**Comment by ZornitsaPesheva** [comment]
Please send the result of these (from the server app) to our email: support@balkan.app
console.log(FamilyTree.isTrial())
console.log(FamilyTree.VERSION)
and ask for a meeting.
