### ISSUE TITLE
Template calculated value

### ISSUE THREAD

**Issue by aesislabs** [BALKANGraph/FamilyTreeJS#74]
In one of my templates I need to draw a progressbar in SVG and want to size a box according to a field value (the progress).

Do you have any idea on how to do something like this ?

**Comment by ZornitsaPesheva** [comment]
Using foreignobject, you can have any HTML in your nodes:
https://balkan.app/OrgChartJS/Docs/Fields#html

**Comment by aesislabs** [comment]
Thank you for your quick answer
