### ISSUE TITLE
Problem in adding new nodes

### ISSUE THREAD

**Issue by MuhammadWasi819** [BALKANGraph/FamilyTreeJS#76]
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/133983418/4f7bba11-53d3-4e69-807e-bc5a7c413e60)
Check this image when click on parent node either mother or father I am getting the same data in console that is pids array!
Similarly if we have to add the spouse I am getting the same data that's why I am not be able to determine the relative via its spouse or its a parent?
Please provide me the solution with the example link

Regards,
Muhammad W.

**Comment by ZornitsaPesheva** [comment]
If the main purpose is to save the changes in the database, you can see in this server side example how you can do that:
[ZornitsaPesheva/FTforNodeJSpug (github.com)](https://github.com/ZornitsaPesheva/FTforNodeJSpug)
