### ISSUE TITLE
Custom Layout

### ISSUE THREAD

**Issue by isswarya-ideassion** [BALKANGraph/FamilyTreeJS#77]
Hello, I'm trying to re-structure the family tree into bowtie chart. And when i looked up i was able to do that for orgChart but not for family tree. Is it possible to do it ?

ref: 
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/111696809/ede6798e-ef14-4bbb-9038-d7f3fd66e49f)

**Comment by ZornitsaPesheva** [comment]
No cense to do that with Family Tree JS.
If it is possible at all it would be much more complicated than making it with Org Chart JS.
The idea of the Family Tree JS is that you can have partners and both partners have common children,
