### ISSUE TITLE
Remove event listener

### ISSUE THREAD

**Issue by pandabytes** [BALKANGraph/FamilyTreeJS#78]
Hello!

After registering a callback to certain events like `familyTree.onUpdateNode`, how do I unregister the same callback from `familyTree`?

**Comment by ZornitsaPesheva** [comment]
Created a code demo for you:
https://code.balkan.app/family-tree-js/remove-events-on-update#JS

**Comment by pandabytes** [comment]
Thanks @ZornitsaPesheva . The example you show removes the "update" listener from all FamilyTree objects right? What if I only want remove the "update" listener from one FamilyTree object? For example

```ts
function updateListener_1(args) {}
function updateListener_2(args) {}

const familyTree_1 = new FamilyTree(...);
const familyTree_2 = new FamilyTree(...);

familyTree_1.onUpdateNode(updateListener_1);
familyTree_2.onUpdateNode(updateListener_2);

// Is it possible to unresgiter updateListener_1 from familyTree_1?
```

**Comment by plamen-peshev** [comment]
we have added [removeListener](https://balkan.app/FamilyTreeJS/API/classes/FamilyTree#) method for you

clear your browser cache and test [this code demo ](https://code.balkan.app/result/remove-event-listener)

**Comment by pandabytes** [comment]
Nice! Thank you so much!
