### ISSUE TITLE
Unexpected rendering : Everything is gray

### ISSUE THREAD

**Issue by sylvain-guillet** [BALKANGraph/FamilyTreeJS#80]
I've created an minimal example but the UI is gray : 
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/16576963/b415e340-8940-40e0-9f06-f8a6441b810f)

My code :
``` HTML
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
    <script src="familytree.js"></script>
  </head>
  <body>
    <div style="width:100%; height:700px;" id="tree"></div>
    <script>
        let family = new FamilyTree(document.getElementById("tree"), {
            nodeBinding: {
                field_0: "name"
            },
            nodes: [
                { id: 1, pids: [2], name: "Amber McKenzie" },
                { id: 2, pids: [1], name: "Ava Field" },
                { id: 3, mid: 1, fid: 2, name: "Peter Stevens" }  
            ]
        });
    </script> 
  </body>
</html>
```

**Comment by ZornitsaPesheva** [comment]
You need to add "gender" property to the nodes.

**Comment by sylvain-guillet** [comment]
> You need to add "gender" property to the nodes.

Thank you, it works and obviously it's logic but you should update your example in the 'getting started' section : 
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/16576963/1e7e85f4-b20b-4dc4-a59f-927e8b8d12b3)

**Comment by ZornitsaPesheva** [comment]
Done! Thank you!
