### ISSUE TITLE
What should I do if I want to place the male on the right?

### ISSUE THREAD

**Issue by wanyouyu** [BALKANGraph/FamilyTreeJS#81]
Now it's on the left. I want to place the male on the right

**Comment by ZornitsaPesheva** [comment]
You need to change the field definition in the template:
Example:
```
    FamilyTree.templates.tommy_male.field_0 = 
        '<text ' + FamilyTree.attr.width + ' ="230" style="font-size: 18px;font-weight:bold;" fill="#ffffff" **x="210"** y="90" **text-anchor="end"**>{val}</text>';
```

**Comment by wanyouyu** [comment]
I want to place men on the right and women on the left, because in China, people who place them on the right are more prestigious. I originally intended to rely on_ SetPositions to modify their positioning, but its positioning data seems to come from OrgChartJS. I think it won't work if just modifying <text>? right?  Perhaps my understanding of the entire source code is insufficient.

**Comment by wanyouyu** [comment]
Thank you very much. It worked and solved a big problem for me.
