### ISSUE TITLE
Question : How to save Family Tree in database ?

### ISSUE THREAD

**Issue by dahut07** [BALKANGraph/FamilyTreeJS#82]
Hello,

In the documentation i didn't found an example of saving the Tree in database (SQLite for  eg).
How to proceed ?

Maybe this way but it is not elegant : 
1) Intercept the "onUpdateNode" event
2) Export the tree in CSV
`let csv = OrgChart.convertNodesToCsv(family.config.nodes);  `
3) Save CSV in database with my backend code 

And Import CSV from database when i want to open my project?
```
 StringBuilder sb = new StringBuilder();
 using (var p = ChoCSVReader.LoadText(myJsonFromDb)
     .WithFirstLineHeader()
     )
 {
     using (var w = new ChoJSONWriter(sb))
         w.Write(p);
 }
```

What is the best way to do this?

Thanks.

**Comment by ZornitsaPesheva** [comment]
Here we have server side examples:
https://balkan.app/FamilyTreeJS/Docs/GitHub
