### ISSUE TITLE
Right - click

### ISSUE THREAD

**Issue by Kemmm2001** [BALKANGraph/FamilyTreeJS#83]
Can I get node is by right -clicking? And can there be functions like left click?
Thank

**Comment by ZornitsaPesheva** [comment]
node click: https://code.balkan.app/family-tree-js/open-hyperlink-on-node-click#JS
right click: https://code.balkan.app/family-tree-js/right-click#JS

**Comment by Kemmm2001** [comment]
I want to do it on vuejs. Is that possible?

**Comment by ZornitsaPesheva** [comment]
should be the same

**Comment by Kemmm2001** [comment]
I want to directly see the relationship between any two people
(grandparents, parents, or siblings), is there any way to do that?

**Comment by ZornitsaPesheva** [comment]
You can use Clinks to show any relation:
https://balkan.app/FamilyTreeJS/Docs/Clink

**Comment by Kemmm2001** [comment]
because of the large number of genealogical members. So the nodes are lying
close to each other and it's not pretty. Is there any best way to fix
them?[image:
398523315_1831971833922121_9108270123460265159_n.png][image:
385557042_3505321073019573_3880900290590471864_n - Copy.png]

**Comment by ZornitsaPesheva** [comment]
Please create a code example here:
https://code.balkan.app/familytreejs/getting-started#JS

**Comment by Kemmm2001** [comment]
I am implementing a search function. But I don't want to close the tree
like this. How do I remove this function and get the full tree



 [image: image.png]

**Comment by ZornitsaPesheva** [comment]
Please create an example in our Code app and post the link here.
