### ISSUE TITLE
load from js file

### ISSUE THREAD

**Issue by zeraati** [BALKANGraph/FamilyTreeJS#88]
I use this code to load data from json

var nodes = JSON.parse(jsonData);
if (FamilyTree.events.publish("import", [family, nodes]) != 0) {
    family._putInUndoStack();
    family.clearRedo();
    family.config.nodes = nodes;
    FamilyTree.events.publish("updated", [family]);
    family.filterUI.update();
    family.draw();
}

is it right?

**Comment by ZornitsaPesheva** [comment]
Do I understand right that you need to load data from a json file?

**Comment by ZornitsaPesheva** [comment]
family.load(json)

**Comment by zeraati** [comment]
I think that due to the fact that receiving information from the API is
delayed - I think that the load was not done correctly
I will check again and announce the result by night
