### ISSUE TITLE
Changing the style of the node menu

### ISSUE THREAD

**Issue by zeraati** [BALKANGraph/FamilyTreeJS#89]
The node menu is as follows
![Screenshot_3](https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/84ddbc12-2d58-4027-9764-43b84f260853)

And I want to style it so that it looks like the picture below
![Screenshot_2](https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/c15d24e5-2e5e-46c4-b9c3-adbaddc8a1a4)

How can I change the style of node menus?

**Comment by ZornitsaPesheva** [comment]
This is not possible out of the box but you can try to do it with CSS.
The color you can set this way: 
edit: { text: "Edit", icon: OrgChart.icon.edit(18, 18, '#039BE5')  },

**Comment by zeraati** [comment]
So, do I have to change the source code to display the menu like this?
It is not possible to customize the appearance without changing the source?

Given that my requested menu shape works well - is it possible to add it as a default in the menus in the app?
There is already an example circular menu in the app, this should be added as well

**Comment by ZornitsaPesheva** [comment]
If you change the source code, we may not be able to support you.
We cannot add all examples in the source code as we are trying to keep it simple and lightweight.
