### ISSUE TITLE
On exporting in PDF the tree doesn't show all nodes 

### ISSUE THREAD

**Issue by daopapp** [BALKANGraph/FamilyTreeJS#9]
When i try to export the tree, they doesn't show all nodes on PDF printing.
I know that for UX it's better the tree collapse for a better view.
But when i'm exporting, the system should show all nodes.
There is a way to configure this?

**Comment by ZornitsaPesheva** [comment]
Could you please isolate the issue in Code?
https://code.balkan.app/orgchartjs/getting-started#JS

**Comment by daopapp** [comment]
Hi, i've created this code to show the issue:
https://code.balkan.app/exporting-pdf#JS

**Comment by ZornitsaPesheva** [comment]
You'd like the export to show the Samson's parents also?

**Comment by daopapp** [comment]
Yes, i know that on use o familyTree it's complicated to show all nodes on window.
But on export it's important to show all nodes(parents and sons) of entire tree.

**Comment by ZornitsaPesheva** [comment]
What you can do is to export twice. Export, expand other parents and then export again.
But you can't show all nodes in one page.

**Comment by daopapp** [comment]
ok, sad about that.
