### ISSUE TITLE
Family - Change node color from a button in the Edit Form

### ISSUE THREAD

**Issue by zeraati** [BALKANGraph/FamilyTreeJS#90]
https://code.balkan.app/code-of-the-week/change-the-node-color-from-a-button-in-the-edit-form#JS

How is it used for the family?

**Comment by ZornitsaPesheva** [comment]
Created a code demo for you: https://code.balkan.app/family-tree-js/change-node-color-from-edit-form#JS

**Comment by zeraati** [comment]
It did not work properly
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/11840312-b2a9-4df9-8bb4-7b2894174d05)

**Comment by ZornitsaPesheva** [comment]
You haven't added the CSS: https://code.balkan.app/family-tree-js/change-node-color-from-edit-form#CSS
