### ISSUE TITLE
remove node avatar

### ISSUE THREAD

**Issue by zeraati** [BALKANGraph/FamilyTreeJS#91]
How to remove the registered avatar for a node?
There is no remove button
When the avatar text box is empty and the save button is pressed, the black avatar is shown.
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/f9b20eff-3602-44e9-a449-cc4bd4e14fca)

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue in a code example here:
https://code.balkan.app/familytreejs/getting-started#JS

**Comment by zeraati** [comment]
https://code.balkan.app/remove-image#JS

https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/70b33fc1-4a65-44ea-9e7d-997ff77680f3

**Comment by ZornitsaPesheva** [comment]
Do you have images in your data?

**Comment by ZornitsaPesheva** [comment]
Do you expect when you delete the hyperlink to the image, the box to be deleted too?

**Comment by zeraati** [comment]
yes
When the avatar | upload image text box is empty or has no text, the image box should not be displayed
