### ISSUE TITLE
rtl mode - arabic

### ISSUE THREAD

**Issue by zeraati** [BALKANGraph/FamilyTreeJS#93]
What change is necessary for the direction to change from right to left (Arabic)?

**Comment by ZornitsaPesheva** [comment]
Here is a Code demo: https://code.balkan.app/family-tree-js/rtl#JS

**Comment by zeraati** [comment]
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/7b70f783-a8a1-496a-b3f5-6fe49511a465)
It is good for long texts, but for short texts it takes a lot of space from the side

**Comment by zeraati** [comment]
I use this:
        FamilyTree.templates.tommy_male.field_0 = '<text data-width="130" data-text-overflow="multiline" style="font-size: 14px;" fill="#ffffff" x="230" y="90" text-anchor="end">{val}</text>';
        FamilyTree.templates.tommy_female.field_0 = '<text data-width="130" data-text-overflow="multiline" style="font-size: 14px;" fill="#ffffff" x="230" y="90" text-anchor="end">{val}</text>';

it worked

**Comment by ZornitsaPesheva** [comment]
Yes, you can change text-anchor as you need it.

**Comment by zeraati** [comment]
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/d840aa95-4c72-44a0-8207-c5b48ece88c3)
How can I move three points to the end and change its size and color?

**Comment by ZornitsaPesheva** [comment]
You need to change the last two values in the matrix here:
    
OrgChart.templates.ana.nodeMenuButton = 
        '<g style="cursor:pointer;" transform="matrix(1,0,0,1,225,105)" data-ctrl-n-menu-id="{id}">'
            + '<rect x="-4" y="-10" fill="#000000" fill-opacity="0" width="22" height="22"></rect>'
            + '<circle cx="0" cy="0" r="2" fill="#ffffff"></circle>'
            + '<circle cx="7" cy="0" r="2" fill="#ffffff"></circle><circle cx="14" cy="0" r="2" fill="#ffffff"></circle>'
        + '</g>';
