### ISSUE TITLE
add menu (top right corner) item dynamically

### ISSUE THREAD

**Issue by zeraati** [BALKANGraph/FamilyTreeJS#94]
How can I add items to the menu (top right corner) dynamically after page loaded?
![Untitled](https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/cdf87057-da03-4d70-90f6-192e7aa1347e)

**Comment by ZornitsaPesheva** [comment]
Please explain what you need to do with screenshots if needed.

**Comment by ZornitsaPesheva** [comment]
Please check if this demo is what you need:
https://code.balkan.app/family-tree-js/change-config#JS
