### ISSUE TITLE
`replaceIds` doesn't work with multiple ids

### ISSUE THREAD

**Issue by pandabytes** [BALKANGraph/FamilyTreeJS#96]
Hello. Thank you for the great library!

# Issue
I ran into an issue with `familyTree.replaceIds`. This method throws an exception when I pass in multiple ids like this: `familyTree.replaceIds({ 1: 'a', 2: 'b' })`. However it works fine if I break the ids into individual objects so like this:
```js
familyTree.replaceIds({ 1: 'a' });
familyTree.replaceIds({ 2: 'b' });
```

The exception is displayed in the chrome devtool console:
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/18756606/65aef267-6de0-4420-8504-04d83c1a8102)

# Code example
```html
<!--HTML-->
<script src="https://balkan.app/js/FamilyTree.js"></script>
<button id="btn">Test</button>
<div id="tree"></div>
```

```js
//JavaScript
var family = new FamilyTree(document.getElementById("tree"), {
    mouseScrool: FamilyTree.action.none,
    nodeBinding: {
        field_0: "name"
    },
    nodeTreeMenu: true,
    nodes: [
        { id: 1, pids: [2], name: "Amber McKenzie", gender: "female" },
        { id: 2, pids: [1], name: "Ava Field", gender: "male" },
    ]
});

document.getElementById("btn").addEventListener("click", function () {
    // This throws an exception 
    family.replaceIds({1: 'a', 2: 'b'});

   // This doesn't throw an exception
    family.replaceIds({1: 'a'});
    family.replaceIds({2: 'b'});
});
```

**Comment by ZornitsaPesheva** [comment]
This method is used to replace ids with the those generated in the backend:
https://github.com/plamen-peshev/FamilyTreeJSGenerateNewNodesIdsFromServerSide/tree/master/FamilyTreeJSGenerateNewNodesIdsFromServerSide

**Comment by pandabytes** [comment]
Yep. I understand what method does but I'm unsure of how to call this method correctly because, as described above
```js
// Usage 1 - Throw exception
family.replaceIds({1: 'a', 2: 'b'});

// Usage 2 - Ok
family.replaceIds({1: 'a'});
family.replaceIds({2: 'b'});
```

**Comment by ZornitsaPesheva** [comment]
I don't know how exactly the method works, but the ids that are replaced are generated from the chart for the new nodes.
We don't replace already existing nodes, as their id's are already taken from the server.
Please try the same case as in our GitHub example.

**Comment by pandabytes** [comment]
Perhaps I'm not being cleared. I understand the purpose of the method, but it throws an exception when I pass an object with multiple ids in which I think it's supposed to do. So my question is, is this a bug?

**Comment by ZornitsaPesheva** [comment]
Yes, may be it is a bug. We will check and will write you again.

**Comment by plamen-peshev** [comment]
We have addressed the issue in the lates release

You can test this [Code demo ](https://code.balkan.app/replaceids-doesnt-work-with-multiple-ids#JS) (before testing lcear your browser cache)

**Comment by pandabytes** [comment]
Thank you!
