### ISSUE TITLE
Default data for first node

### ISSUE THREAD

**Issue by pandabytes** [BALKANGraph/FamilyTreeJS#97]
Hello. Is there a way to provide default properties and values to the very first node? Specifically I'm referring to when the family tree is empty and there is this message `It's lonely here, add your first node`. When clicking on this message, it adds an empty gray node. I would like to know if it's possible to provide default data to this very first node, instead of the empty gray node.

![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/18756606/cda117c2-36c6-4eff-b696-7012f1351ece)

![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/18756606/8f610b16-05c0-4060-b9b0-822af84fc976)

**Comment by ZornitsaPesheva** [comment]
Here is a code demo:
https://code.balkan.app/family-tree-js/custom-first-node#JS

**Comment by pandabytes** [comment]
Awesome, thanks for the example!
