### ISSUE TITLE
Increase the size of the menu button

### ISSUE THREAD

**Issue by zeraati** [BALKANGraph/FamilyTreeJS#98]
How can I increase the size of the menu button?
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/b42963e6-04d9-4490-b8c3-e6fb2fb61fce)

**Comment by ZornitsaPesheva** [comment]
You need to change the buttons definition of the [base](https://balkan.app/FamilyTreeJS/Docs/PredefinedTemplates#baseFTTemplate) template.
Click on [Get the source code of base template](https://balkan.app/FamilyTreeJS/Docs/PredefinedTemplates#)
main menu button - try changing width and height for the **menuButton**
node menu button  - try changing width and height for base_node_menu in the **base** definition

**Comment by zeraati** [comment]
I changed the height of the menu button
But it is still displayed based on the height of the default template
https://code.balkan.app/change-base-template-menu-button#JS
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/219537de-9ebc-4035-b59a-14ab11629c91)

**Comment by ZornitsaPesheva** [comment]
Please send a screenshot of the expected result.

**Comment by zeraati** [comment]
this is 10 px
![10px](https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/1e2384eb-a310-43a4-aaee-db73eb4dd15e)

**Comment by zeraati** [comment]
I changed the template in code to height 10px, but still the default size 3 is loaded in view
Only if I change the codes in the inspect of chrome, the correct height will be displayed

**Comment by ZornitsaPesheva** [comment]
Yes, sorry. You need to change it for the current template:
https://code.balkan.app/family-tree-js/menu-button-size#JS

**Comment by zeraati** [comment]
> You need to change the buttons definition of the [base](https://balkan.app/FamilyTreeJS/Docs/PredefinedTemplates#baseFTTemplate) template. Click on **Get the source code of base template** main menu button - try changing width and height for the **menuButton** node menu button - try changing width and height for base_node_menu in the **base** definition

base_node_menu has no length or width
How can I make it bigger?
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/c5a8272f-f2b5-4c55-b240-e796e99d532b)

**Comment by ZornitsaPesheva** [comment]
Edited the code demo:
https://code.balkan.app/family-tree-js/menu-button-size#JS
Added **transform="matrix(1.5,0,0,1.5,-10,-10)"** to change the button

**Comment by zeraati** [comment]
https://code.balkan.app/family-tree-js/menu-button-size#JS
Clicking on menu and menu node not worked

**Comment by ZornitsaPesheva** [comment]
because the menus are empty;
    menu: {},
    nodeMenu: {}

You can add menu options:
    nodeMenu: {
        details: { text: "Details" },
        edit: { text: "Edit" },
        add: { text: "Add" },
        remove: { text: "Remove" }
    },
    menu: {
        pdf: { text: "Export PDF" },
        png: { text: "Export PNG" },
        svg: { text: "Export SVG" },
        csv: { text: "Export CSV" }
    },

**Comment by ZornitsaPesheva** [comment]
I have changed the color:
https://code.balkan.app/family-tree-js/menu-button-size#JS
