### ISSUE TITLE
Choose a name for the export file

### ISSUE THREAD

**Issue by zeraati** [BALKANGraph/FamilyTreeJS#99]
How can I set the file name when outputting data in Jason format?
Currently, all outputs with the same name are received

**Comment by zeraati** [comment]
![image](https://github.com/BALKANGraph/FamilyTreeJS/assets/21211444/e20aec26-d8a5-4077-9ef6-a0dedfe3ab8b)
All files are saved with the name "FamilyTree.json"

**Comment by ZornitsaPesheva** [comment]
Here is a code demo:
https://code.balkan.app/family-tree-js/export-json-file-mane#JS
